version: "3.3"

networks:
  calendar_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  calendar-event:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    networks:
      - calendar_net
    restart: unless-stopped

  training:
    build: .
    volumes:
      - ./:/app
    command: python train.py
    networks:
      - calendar_net

  save_model:
    build: .
    volumes:
      - ./:/app
    command: python save_model.py
    networks:
      - calendar_net

  client:
    build: .
    volumes:
      - ./:/app
    command: python client.py ws://143.110.238.245:8000/stream
    networks:
      - calendar_net
